image: ghcr.io/cirruslabs/flutter

stages:
  - androidBuild
  - androidDeploy

buildStagging:
  stage: androidBuild
  before_script:
    - flutter clean
    - rm pubspec.lock
    - flutter pub get
    - flutter packages pub run build_runner build --delete-conflicting-outputs
  script:
    - flutter test --plain-name "test insert person"
#    - cd android
#    - pwd
#    - ls
#    - bundle exec fastlane android_build_apk_stagging
#    - fastlane move_files
#    - fastlane upload_to_drive_and_send_mattermost
#  artifacts:
#    paths:
#      - build/artifacts/
#  tags:
#    - flutter