image: ghcr.io/cirruslabs/flutter

stages:
  - buildFlutter

buildStagging:
  stage: buildFlutter
    - flutter clean
    - rm pubspec.lock
    - flutter pub get
    - flutter packages pub run build_runner build --delete-conflicting-outputs
    - flutter test --plain-name "test insert person"
    - flutter test --plain-name "test insert multi person"
    - flutter test --plain-name "test update person"
    - flutter test --plain-name "test delete person"
    - make build_apk_ip
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
