image: ghcr.io/cirruslabs/flutter

stages:
  - androidBuild
  - androidDeploy

buildStagging:
  stage: androidBuild
  before_script:
    - flutter clean
    - rm pubspec.lock
    - flutter pub get
    - flutter packages pub run build_runner build --delete-conflicting-outputs
  script:
    - flutter test --plain-name "test insert person"
    - flutter test --plain-name "test insert multi person"
    - flutter test --plain-name "test update person"
    - flutter test --plain-name "test delete person"
    - make build_apk_ip
  artifacts:
    paths:
      - build/artifacts/
  tags:
    - flutter