image: ghcr.io/cirruslabs/flutter

pipelines:
  branches:
    main:
      - step:
          name: Build and Test
          script:
            - flutter clean
            - flutter pub upgrade
            - flutter pub get
            - flutter test --plain-name "test insert person"
            - flutter test --plain-name "test insert multi person"
            - flutter test --plain-name "test update person"
            - flutter test --plain-name "test delete person"
            - make build_apk_ip
