image: cirrusci/flutter:latest

pipelines:
  branches:
    main:
      - step:
          name: Build and Test
          script:
            - flutter clean
            - flutter pub upgrade
            - flutter pub get
