image: mobiledevops/flutter-sdk-image:3.10.3

pipelines:
  branches:
    main:
      - step:
          name: Build and Test
          script:
            - flutter clean
            - flutter pub upgrade
            - flutter pub get
