image: cirrusci/flutter:latest

pipelines:
  branches:
    main:
      - step:
          name: Build and Test
          script:
            - flutter pub get
            - flutter test
            - flutter build apk
            - echo "Build and Test completed on main branch"