image: mobiledevops/flutter-sdk-image:3.10.3
pipelines:
  branches:
    main:
      - step:
          script:
            - echo "This script runs only on commit to the main branch."
            - flutter pub get
            - flutter build apk --release



