name: workdflow_cicd_practice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hello world
        run: echo "Hello World"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye
        run: echo "goodbye"
        shell: bash
  sqflite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: flutter pub get
        name: setup sqflite
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter test --plain-name "1"
        shell: bash


